Require Export euclidean__axioms.
Definition Out (A : euclidean__axioms.Point) (B : euclidean__axioms.Point) (C : euclidean__axioms.Point)  := exists X, (euclidean__axioms.BetS X A C) /\ (euclidean__axioms.BetS X A B).
Definition Lt (A : euclidean__axioms.Point) (B : euclidean__axioms.Point) (C : euclidean__axioms.Point) (D : euclidean__axioms.Point)  := exists X, (euclidean__axioms.BetS C X D) /\ (euclidean__axioms.Cong C X A B).
Definition Midpoint (A : euclidean__axioms.Point) (B : euclidean__axioms.Point) (C : euclidean__axioms.Point)  := (euclidean__axioms.BetS A B C) /\ (euclidean__axioms.Cong A B B C).
Definition CongA (A : euclidean__axioms.Point) (B : euclidean__axioms.Point) (C : euclidean__axioms.Point) (a : euclidean__axioms.Point) (b : euclidean__axioms.Point) (c : euclidean__axioms.Point)  := exists U V u v, (euclidean__defs.Out B A U) /\ ((euclidean__defs.Out B C V) /\ ((euclidean__defs.Out b a u) /\ ((euclidean__defs.Out b c v) /\ ((euclidean__axioms.Cong B U b u) /\ ((euclidean__axioms.Cong B V b v) /\ ((euclidean__axioms.Cong U V u v) /\ (euclidean__axioms.nCol A B C))))))).
Definition AdjacentAngle (A : euclidean__axioms.Point) (B : euclidean__axioms.Point) (C : euclidean__axioms.Point) (D : euclidean__axioms.Point) (E : euclidean__axioms.Point) (F : euclidean__axioms.Point)  := (B = E) /\ ((euclidean__axioms.BetS A B F) /\ (euclidean__defs.Out B D C)).
Definition VA (A : euclidean__axioms.Point) (B : euclidean__axioms.Point) (C : euclidean__axioms.Point) (D : euclidean__axioms.Point) (E : euclidean__axioms.Point) (F : euclidean__axioms.Point)  := (B = E) /\ ((euclidean__axioms.BetS A B D) /\ (euclidean__axioms.BetS C B F)).
Definition Supp (A : euclidean__axioms.Point) (B : euclidean__axioms.Point) (C : euclidean__axioms.Point) (D : euclidean__axioms.Point) (F : euclidean__axioms.Point)  := (euclidean__defs.Out B C D) /\ (euclidean__axioms.BetS A B F).
Definition Per (A : euclidean__axioms.Point) (B : euclidean__axioms.Point) (C : euclidean__axioms.Point)  := exists X, (euclidean__axioms.BetS A B X) /\ ((euclidean__axioms.Cong A B X B) /\ ((euclidean__axioms.Cong A C X C) /\ (euclidean__axioms.neq B C))).
Definition Perp__at (P : euclidean__axioms.Point) (Q : euclidean__axioms.Point) (A : euclidean__axioms.Point) (B : euclidean__axioms.Point) (C : euclidean__axioms.Point)  := exists X, (euclidean__axioms.Col P Q C) /\ ((euclidean__axioms.Col A B C) /\ ((euclidean__axioms.Col A B X) /\ (euclidean__defs.Per X C P))).
Definition Perp (P : euclidean__axioms.Point) (Q : euclidean__axioms.Point) (A : euclidean__axioms.Point) (B : euclidean__axioms.Point)  := exists X, euclidean__defs.Perp__at P Q A B X.
Definition InAngle (A : euclidean__axioms.Point) (B : euclidean__axioms.Point) (C : euclidean__axioms.Point) (P : euclidean__axioms.Point)  := exists X Y, (euclidean__defs.Out B A X) /\ ((euclidean__defs.Out B C Y) /\ (euclidean__axioms.BetS X P Y)).
Definition OS (P : euclidean__axioms.Point) (Q : euclidean__axioms.Point) (A : euclidean__axioms.Point) (B : euclidean__axioms.Point)  := exists X U V, (euclidean__axioms.Col A B U) /\ ((euclidean__axioms.Col A B V) /\ ((euclidean__axioms.BetS P U X) /\ ((euclidean__axioms.BetS Q V X) /\ ((euclidean__axioms.nCol A B P) /\ (euclidean__axioms.nCol A B Q))))).
Definition IO (A : euclidean__axioms.Point) (B : euclidean__axioms.Point) (C : euclidean__axioms.Point) (D : euclidean__axioms.Point)  := (euclidean__axioms.BetS A B C) /\ ((euclidean__axioms.BetS A B D) /\ ((euclidean__axioms.BetS A C D) /\ (euclidean__axioms.BetS B C D))).
Definition isosceles (A : euclidean__axioms.Point) (B : euclidean__axioms.Point) (C : euclidean__axioms.Point)  := (euclidean__axioms.Triangle A B C) /\ (euclidean__axioms.Cong A B A C).
Definition Cut (A : euclidean__axioms.Point) (B : euclidean__axioms.Point) (C : euclidean__axioms.Point) (D : euclidean__axioms.Point) (E : euclidean__axioms.Point)  := (euclidean__axioms.BetS A E B) /\ ((euclidean__axioms.BetS C E D) /\ ((euclidean__axioms.nCol A B C) /\ (euclidean__axioms.nCol A B D))).
Definition LtA (A : euclidean__axioms.Point) (B : euclidean__axioms.Point) (C : euclidean__axioms.Point) (D : euclidean__axioms.Point) (E : euclidean__axioms.Point) (F : euclidean__axioms.Point)  := exists U X V, (euclidean__axioms.BetS U X V) /\ ((euclidean__defs.Out E D U) /\ ((euclidean__defs.Out E F V) /\ (euclidean__defs.CongA A B C D E X))).
Definition TG (A : euclidean__axioms.Point) (B : euclidean__axioms.Point) (C : euclidean__axioms.Point) (D : euclidean__axioms.Point) (E : euclidean__axioms.Point) (F : euclidean__axioms.Point)  := exists X, (euclidean__axioms.BetS A B X) /\ ((euclidean__axioms.Cong B X C D) /\ (euclidean__defs.Lt E F A X)).
Definition TT (A : euclidean__axioms.Point) (B : euclidean__axioms.Point) (C : euclidean__axioms.Point) (D : euclidean__axioms.Point) (E : euclidean__axioms.Point) (F : euclidean__axioms.Point) (G : euclidean__axioms.Point) (H : euclidean__axioms.Point)  := exists X, (euclidean__axioms.BetS E F X) /\ ((euclidean__axioms.Cong F X G H) /\ (euclidean__defs.TG A B C D E X)).
Definition RT (A : euclidean__axioms.Point) (B : euclidean__axioms.Point) (C : euclidean__axioms.Point) (D : euclidean__axioms.Point) (E : euclidean__axioms.Point) (F : euclidean__axioms.Point)  := exists X Y Z U V, (euclidean__defs.Supp X Y U V Z) /\ ((euclidean__defs.CongA A B C X Y U) /\ (euclidean__defs.CongA D E F V Y Z)).
Definition Meet (A : euclidean__axioms.Point) (B : euclidean__axioms.Point) (C : euclidean__axioms.Point) (D : euclidean__axioms.Point)  := exists X, (euclidean__axioms.neq A B) /\ ((euclidean__axioms.neq C D) /\ ((euclidean__axioms.Col A B X) /\ (euclidean__axioms.Col C D X))).
Definition CR (A : euclidean__axioms.Point) (B : euclidean__axioms.Point) (C : euclidean__axioms.Point) (D : euclidean__axioms.Point)  := exists X, (euclidean__axioms.BetS A X B) /\ (euclidean__axioms.BetS C X D).
Definition TP (A : euclidean__axioms.Point) (B : euclidean__axioms.Point) (C : euclidean__axioms.Point) (D : euclidean__axioms.Point)  := (euclidean__axioms.neq A B) /\ ((euclidean__axioms.neq C D) /\ ((~(euclidean__defs.Meet A B C D)) /\ (euclidean__defs.OS C D A B))).
Definition Par (A : euclidean__axioms.Point) (B : euclidean__axioms.Point) (C : euclidean__axioms.Point) (D : euclidean__axioms.Point)  := exists U V u v X, (euclidean__axioms.neq A B) /\ ((euclidean__axioms.neq C D) /\ ((euclidean__axioms.Col A B U) /\ ((euclidean__axioms.Col A B V) /\ ((euclidean__axioms.neq U V) /\ ((euclidean__axioms.Col C D u) /\ ((euclidean__axioms.Col C D v) /\ ((euclidean__axioms.neq u v) /\ ((~(euclidean__defs.Meet A B C D)) /\ ((euclidean__axioms.BetS U X v) /\ (euclidean__axioms.BetS u X V)))))))))).
Definition SumA (A : euclidean__axioms.Point) (B : euclidean__axioms.Point) (C : euclidean__axioms.Point) (D : euclidean__axioms.Point) (E : euclidean__axioms.Point) (F : euclidean__axioms.Point) (P : euclidean__axioms.Point) (Q : euclidean__axioms.Point) (R : euclidean__axioms.Point)  := exists X, (euclidean__defs.CongA A B C P Q X) /\ ((euclidean__defs.CongA D E F X Q R) /\ (euclidean__axioms.BetS P X R)).
Definition PG (A : euclidean__axioms.Point) (B : euclidean__axioms.Point) (C : euclidean__axioms.Point) (D : euclidean__axioms.Point)  := (euclidean__defs.Par A B C D) /\ (euclidean__defs.Par A D B C).
Definition SQ (A : euclidean__axioms.Point) (B : euclidean__axioms.Point) (C : euclidean__axioms.Point) (D : euclidean__axioms.Point)  := (euclidean__axioms.Cong A B C D) /\ ((euclidean__axioms.Cong A B B C) /\ ((euclidean__axioms.Cong A B D A) /\ ((euclidean__defs.Per D A B) /\ ((euclidean__defs.Per A B C) /\ ((euclidean__defs.Per B C D) /\ (euclidean__defs.Per C D A)))))).
Definition RE (A : euclidean__axioms.Point) (B : euclidean__axioms.Point) (C : euclidean__axioms.Point) (D : euclidean__axioms.Point)  := (euclidean__defs.Per D A B) /\ ((euclidean__defs.Per A B C) /\ ((euclidean__defs.Per B C D) /\ ((euclidean__defs.Per C D A) /\ (euclidean__defs.CR A C B D)))).
Definition RC (A : euclidean__axioms.Point) (B : euclidean__axioms.Point) (C : euclidean__axioms.Point) (D : euclidean__axioms.Point) (a : euclidean__axioms.Point) (b : euclidean__axioms.Point) (c : euclidean__axioms.Point) (d : euclidean__axioms.Point)  := (euclidean__defs.RE A B C D) /\ ((euclidean__defs.RE a b c d) /\ ((euclidean__axioms.Cong A B a b) /\ (euclidean__axioms.Cong B C b c))).
Definition ER (A : euclidean__axioms.Point) (B : euclidean__axioms.Point) (C : euclidean__axioms.Point) (D : euclidean__axioms.Point) (a : euclidean__axioms.Point) (b : euclidean__axioms.Point) (c : euclidean__axioms.Point) (d : euclidean__axioms.Point)  := exists X Y Z U x z u w W, (euclidean__defs.RC A B C D X Y Z U) /\ ((euclidean__defs.RC a b c d x Y z u) /\ ((euclidean__axioms.BetS x Y Z) /\ ((euclidean__axioms.BetS X Y z) /\ (euclidean__axioms.BetS W U w)))).
Definition equilateral (A : euclidean__axioms.Point) (B : euclidean__axioms.Point) (C : euclidean__axioms.Point)  := (euclidean__axioms.Cong A B B C) /\ (euclidean__axioms.Cong B C C A).
